### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by ameyrane04** [A4ANK/Fake-Product-Identification#1]
Hey I executed every step correctly, but after deployment the products and records are not getting added and the product is not getting authenticated.
The file are getting scanned 
Please Help, it would be really helpful for me

**Comment by A4ANK** [comment]
Try importing accounts using private key of any account from local blockchain available in Ganache on the Metamask Wallet in the chrome.

**Comment by Yashdeep03** [comment]
hey , i have done exactly same thing which you have told . also imported account using private key from local blockchain, but still i am also facing the same issue as described above . pls help me out . its urgent . Pls make a screen recording of this project running on your machine .

**Comment by ameyrane04** [comment]
> Try importing accounts using private key of any account from local blockchain available in Ganache on the Metamask Wallet in the chrome.
Okay its running now, and everything is almost proper , but when i add sellers or products, the record of those doesn't show up. ( When the pages ask for seller code/manufacturer code to the sellers or products, am i supposed to fill random details or some specific address/code? )
One last step help needed!!

**Comment by A4ANK** [comment]
One can fill the random details as in backend there is only the products' verification.
