### ISSUE TITLE
Issue with quering the blockchain

### ISSUE THREAD

**Issue by Devaansh-Kumar** [A4ANK/Fake-Product-Identification#2]
Hey A4ANK,
Whenever I use the query seller tab under manufacture, after I put the manufacture code, I don't get any results(assuming manufacturer id is same as manufacturer code). Also from where do I add the cosumer because to sell to a consumer I need a consumer code which I cannot see anywhere? Pls respond as quick as possible, its urgent😥

**Comment by satyam1903** [comment]
hey @Devaansh-Kumar  you got any solution

**Comment by Devaansh-Kumar** [comment]
no @satyam1903  not yet

**Comment by A4ANK** [comment]
The project is not implemented completely with all the functionalities. 
e.g. adding a customer separately is not implemented, etc.
One can add the functions accordingly as per the need.

**Comment by A4ANK** [comment]
In Manufacturer segment, the functionality related to adding a manufacturer and querying a manufacturer is implemented completely. 
Only Customer segment is lacking into adding a customer separately. But one can add a new page for customer registration.
